# Website's icon url.
favicon: true

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id: 4kategreen
  twitter_site: https://twitter.com/4kategreen

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo: 

article:
  # Show word count and estimated reading time.
  readtime: true
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: github

# Navigation bar menu links.
menu:
  About: /about
  # Code: /categories/code
  # Life: /categories/life
  Archives: /archives

# Search plugin settings.
search:
  type: insight

# Navigation bar toc settings
toc: false

# Share plugin settings.
share:
  type: 
  install_url:

# Comment plugin settings.
comment:
  type: 
  shortname:

# Other plugins and their settings.
plugins:
  mathjax: true
  katex: false
  gallery: true
  clipboard: true
  google-analytics:
    tracking_id: UA-148602905-1

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/4kategreen
  Twitter:
    icon: fab fa-twitter
    url: https://twitter.com/4kategreen
  Linkedin:
    icon: fab fa-linkedin
    url: https://in.linkedin.com/in/4kategreen

# Links at the bottom of the page.
footer_links:
  GitHub: https://github.com/4kategreen
  Linkedin: https://in.linkedin.com/in/4kategreen
